# This docker-compose file is used to launch a mysql container for jenkins to run unit & integration tests
version: "3.8"

services:
    db:
        image: mysql:8.0.26
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment: 
            MYSQL_DATABASE: ${DOCKER_DB}
            # So you don't have to use root, but you can if you like
            MYSQL_USER: ${DOCKER_USER}
            # You can use whatever password you like
            MYSQL_PASSWORD: ${DOCKER_PASSWORD}
            # Password for root access
            MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
        container_name: db
        volumes:
            - data:/var/lib/mysql
            
volumes:
    data: