# Generated by Django 3.2.5 on 2021-07-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('picture', models.URLField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('deadline', models.DateField(null=True)),
                ('picture', models.URLField(blank=True, max_length=1024)),
                ('complete', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=32)),
                ('lastname', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, max_length=1024)),
                ('encouragement', models.TextField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('deadline', models.DateField(null=True)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
