# Generated by Django 3.2.5 on 2021-07-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210727_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
