# Generated by Django 3.2.5 on 2021-08-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_step_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
