# Generated by Django 3.2.5 on 2021-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_step_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='progress',
            new_name='current_steps_count',
        ),
        migrations.AddField(
            model_name='goal',
            name='total_steps_count',
            field=models.IntegerField(default=0),
        ),
    ]
