# Generated by Django 3.2.5 on 2021-08-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210817_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Recurring')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='encouragement',
            field=models.TextField(blank=True, default='Perseverance, secret of all triumphs - Victor Hugo (Edit this to be anything you want in Profile -> Motivation)', max_length=256),
        ),
    ]
