# Generated by Django 3.2.5 on 2021-08-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210826_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='type',
        ),
        migrations.AddField(
            model_name='step',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
